- name: Copy the Whitelist file to the root user directory
  copy:
    src: templates/whitelist.j2
    dest: /root/whitelist.txt
    mode: 0755
    owner: root
    group: root

- name: Copy the Bash Script file to the root user directory
  copy:
    src: templates/setup_whitelist.j2
    dest: /root/setup_whitelist.sh
    mode: 0755
    owner: root
    group: root

- name: Execute the setup_whitelist.sh script
  shell: "sudo bash /root/setup_whitelist.sh"