- name: check connectivity
  ping:
    data: alive

- name: update and upgrade system
  apt:
    update_cache: yes

- name: install S3cmd and etcd client
  apt:
    pkg:
      - s3cmd
      - etcd-client
    state: present

- name: Copy the config file to the root user directory
  copy:
    src: templates/s3cfg.j2
    dest: /root/.s3cfg
    mode: 0755
    owner: root
    group: root

- name: Create backup directory
  file:
    path: /data/etcd-backup
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create log file
  file:
    path: /var/log/etcd_backup.log
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Copy the cronjob file
  copy:
    src: templates/cron.j2
    dest: /data/etcd-backup/cron.sh
    mode: 0755
    owner: root
    group: root


- name: Backing up ETCD every first minute of every hour
  ansible.builtin.cron:
    name: "Etcd Backup"
    weekday: "*"
    minute: "30"
    hour: "*"
    day: "*"
    month: "*"
    job: "bash /data/etcd-backup/cron.sh"
    state: present
