---
- name: Kubeadm | Check for connectivity
  ping:
    data: alive

- name: Kubeadm | Pull K8S images
  command: kubeadm config images pull --v=5
  register: kubeadm_images
  changed_when: "'Image pull complete' in kubeadm_images.stdout"
  when: "'masters' in group_names"

- name: Kubeadm | Display loadbalancer address
  debug:
    msg: "The address of the 'loadbalancer' host is {{ loadbalancer }}"

- name: Kubeadm | Initialize first control plane node
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --control-plane-endpoint {{ loadbalancer }}:6443 --upload-certs 
  register: kubeadm_init_result
  changed_when: "'Your Kubernetes control-plane has initialized successfully!' not in kubeadm_init_result.stdout"
  when: ansible_hostname == "master-1"

- name: Kubeadm | Create directory in {{ ansible_env.HOME }}/.kube/
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
  when: ansible_hostname == "master-1"

- name: Kubeadm | Copy kubernetes config to home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes
  when: ansible_hostname == "master-1"
