    - name: Add VMware Tanzu Helm repository
      community.kubernetes.helm_repository:
        name: vmware-tanzu
        repo_url: https://vmware-tanzu.github.io/helm-charts
        state: present

    - name: Update Helm repositories
      command: "helm repo update"

    - name: Copy Velero S3 Keys file
      template:
        src: templates/velero.credentials.j2
        dest: /root/velero.credentials

          
    - name: Install or Upgrade Velero Server with Helm
      ansible.builtin.shell: |
        helm upgrade --install velero vmware-tanzu/velero \
        --namespace velero \
        --create-namespace \
        --set-file credentials.secretContents.cloud=/root/velero.credentials \
        --set configuration.backupStorageLocation[0].name=default \
        --set configuration.backupStorageLocation[0].provider=aws \
        --set configuration.backupStorageLocation[0].bucket=king-velero \
        --set configuration.backupStorageLocation[0].config.region=default \
        --set configuration.backupStorageLocation[0].config.s3Url=https://s3.ir-tbz-sh1.arvanstorage.ir \
        --set configuration.backupStorageLocation[0].config.s3ForcePathStyle=true \
        --set configuration.backupStorageLocation[0].default=true \
        --set configuration.volumeSnapshotLocation[0].name=default \
        --set configuration.volumeSnapshotLocation[0].provider=aws \
        --set configuration.volumeSnapshotLocation[0].config.region=default \
        --set initContainers[0].name=velero-plugin-for-aws \
        --set initContainers[0].image=velero/velero-plugin-for-aws:v1.6.1 \
        --set initContainers[0].volumeMounts[0].mountPath=/target \
        --set initContainers[0].volumeMounts[0].name=plugins

    - name: Verify Velero installation
      command: kubectl get pods -n velero
      register: velero_pods
      until: velero_pods.stdout | search("velero")
      retries: 5
      delay: 10

