# tasks/main.yaml

---
- name: Apply ArgoCD manifest to Kubernetes
  ansible.builtin.command:
    cmd: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  register: kubectl_apply
  changed_when: kubectl_apply.rc == 0
  failed_when: kubectl_apply.rc != 0
  args:
    creates: "/tmp/argocd_installed"

