all:
  vars:
    ansible_ssh_port: 1822
  children:
    k8s_cluster:
      children:
        masters:
          hosts:
            master-1:
              ansible_host: 192.168.1.10
              access_ip: 192.168.1.10
              ansible_hostname: master-1
              ansible_ssh_private_key_file: /root/ible/ary.pem
            master-2:
              ansible_host: 192.168.2.10
              access_ip: 192.168.2.10
              ansible_hostname: master-2
              ansible_ssh_private_key_file: /root/ible/ary.pem
            master-3:
              ansible_host: 192.168.3.10
              access_ip: 192.168.3.10
              ansible_hostname: master-3
              ansible_ssh_private_key_file: /root/ible/ary.pem
        workers:
          hosts:
            worker-1:
              ansible_host: 192.168.1.15
              access_ip: 192.168.1.15
              ansible_hostname: worker-1
              ansible_ssh_private_key_file: /root/ible/ary.pem
            worker-2:
              ansible_host: 192.168.2.15
              access_ip: 192.168.2.15
              ansible_hostname: worker-2
              ansible_ssh_private_key_file: /root/ible/ary.pem
            worker-3:
              ansible_host: 192.168.3.15
              access_ip: 192.168.3.15
              ansible_hostname: worker-3
              ansible_ssh_private_key_file: /root/ible/ary.pem

    haproxy:
      hosts:
        haproxy-1:
          ansible_host: 192.168.1.20
          access_ip: 37.32.6.9
          ansible_hostname: haproxy-1
          ansible_ssh_private_key_file: /root/ible/ary.pem
