all:
  vars:
    ansible_ssh_port: 
  children:
    k8s_cluster:
      children:
        masters:
          hosts:
            master-1:
              ansible_host: 
              access_ip: 
              ansible_hostname: master-1
              ansible_ssh_private_key_file: 
            master-2:
              ansible_host: 
              access_ip: 
              ansible_hostname: master-2
              ansible_ssh_private_key_file: 
            master-3:
              ansible_host: 
              access_ip: 
              ansible_hostname: master-3
              ansible_ssh_private_key_file: 
        workers:
          hosts:
            worker-1:
              ansible_host: 
              access_ip: 
              ansible_hostname: worker-1
              ansible_ssh_private_key_file: 
            worker-2:
              ansible_host: 
              access_ip: 
              ansible_hostname: worker-2
              ansible_ssh_private_key_file: 
            worker-3:
              ansible_host: 
              access_ip: 
              ansible_hostname: worker-3
              ansible_ssh_private_key_file: 

    haproxy:
      hosts:
        haproxy-1:
          ansible_host: 
          access_ip: 
          ansible_hostname: haproxy-1
          ansible_ssh_private_key_file: 
