---

- name: Download Helm script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: "/tmp/get_helm.sh"
    mode: "0755"

- name: Run Helm installation script
  command: "/tmp/get_helm.sh"
